apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver-rs
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginxweb
  template:
    metadata:
      labels:
        app: nginxweb
        type: prod
    spec:
      containers:
      - name: web
        image: nginx 1.16-alpine
