apiVersion: v1
kind: Pod
metadata:
  name: webserver
  label:
  app: nginxweb
  type: production
  ver: v1
spec:
  containers:
    - name: web
      image: nginx:1.16-alpine
	- name: curl
	  image: curl
	  command: ["/bin/sh" , "-c" , "while : ;do curl http://localhost:80; sleep 15; done"]
