apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: webserver-rs
spec:
  replica: 3
  selector:
   matchLable:
    app: nginxweb
  template:
   metadata:
    lable:
	 app: nginxweb
	 env: development
	spec:
	 containers:
	  - name: web
	    image: nginx 1.16-alpine
